#!/bin/sh

# welcome message
clear
echo "------------------------------------"
echo "  distro-tools automated installer  "
echo "------------------------------------"
echo

# the actual installer :)
/usr/bin/installer

if [ $? == 0 ]; then
	echo 'Success!'
else
	echo 'Failure!'
	# launch a shell
	/bin/sh
fi

# without this, the system will become a zombie
echo
echo 'Shutdown...'
poweroff
