#!/bin/sh

# welcome message
clear
echo "------------------------------------"
echo "Officine Maya SRL"
echo "Le.Dy 1000 series firmware installer"
echo "------------------------------------"
echo

# all is done by our branded installer (:
/usr/bin/installer

if [ $? == 0 ]; then
	echo 'Success!'
else
	echo 'Failure!'
	# launch a shell
	/bin/sh
fi

# without this, the system will become a zombie
echo
echo 'Shutdown...'
poweroff
